### ISSUE TITLE
Error when trying to connect

### ISSUE THREAD

**Issue by RowanHarley** [ClitherProject/Clither-Server#15]
When trying to connect, I get the following:

    14:36:49 [INFO] /0 (0) has connected to the server!
    14:36:49 [INFO] /0 (0) has connected to the server!
    14:36:52 [INFO] /0 (0) has connected to the server!
    14:36:52 [INFO] /0 (0) has connected to the server!
    14:36:52 [INFO] /0 (0) has disconnected from the server!
    14:36:55 [INFO] /0 (0) has disconnected from the server!
    14:36:55 [INFO] /0 (0) has connected to the server!
    14:36:55 [INFO] /0 (0) has connected to the server!
    14:36:58 [INFO] /0 (0) has disconnected from the server!
    14:36:58 [INFO] /0 (0) has connected to the server!
    14:36:58 [INFO] /0 (0) has connected to the server!
    14:37:01 [INFO] /0 (0) has disconnected from the server!
    14:37:01 [INFO] /0 (0) has connected to the server!
    14:37:01 [INFO] /0 (0) has connected to the server!
    14:37:04 [INFO] /0 (0) has disconnected from the server!
    14:37:04 [INFO] /0 (0) has connected to the server!
    14:37:04 [INFO] /0 (0) has connected to the server!

**Comment by ThunderGemios10** [comment]
Unfortunately, This implementation is still under development.
If you would like to help. Feel free to open a PR.

**Comment by RowanHarley** [comment]
ok then, good luck with the project! Can't help because I don't have a clue how to code in java
