### ISSUE TITLE
will youu

### ISSUE THREAD

**Issue by eralpcicekdagi** [ClitherProject/Clither-Server#2]
Will you add chatbox , skin, and most important node index.js style? Java is hard

**Comment by ThunderGemios10** [comment]
@eralpcicekdagi Java is easy to learn, Rest assured.. It is similar to C# and Python..
I will try to make the codes user friendly as possible.. As of now adding a chatbox is a client-side modifications and it is quite illegal, Skins is planned to be on Clither soon,

**Comment by eralpcicekdagi** [comment]
I dont know how to start java in putty

**Comment by eralpcicekdagi** [comment]
is it like node index.js ?

**Comment by ThunderGemios10** [comment]
@eralpcicekdagi Putty? You don't start Java in putty.. Just download Java JDK 8 and download Eclipse or Intellij or Netbeans, It is your choice.
