### ISSUE TITLE
Question about API and repo

### ISSUE THREAD

**Issue by Willsr71** [ClitherProject/Clither-Server#5]
Is there any particular reason why the API is in a separate repository? It makes things slightly more inconvenient when trying to fix an issue or add things. This would not be quite a large issue if the repo was not down constantly. As a result [dependency resolution fails and there goes the build](https://jenkins.willsr71.net/job/Clither-Server/1/console).

If you want to keep the API in a seperate repo, than please get a functional repo. If necessary I can provide [my repo](https://repo.willsr71.net/) as a replacement (currently 16 day uptime, before that 53 days).

**Comment by ThunderGemios10** [comment]
@Willsr71 That's because my maven repo, (repo.thundergemios10.com) is down. Because i coulden't pay anymore, Since you have jenkins and a repo, I would be glad to host it there. Make a pull request to change the pom.xml file.

Cheers !

**Comment by ThunderGemios10** [comment]
@Willsr71 Also, Would you like to join the project's development ? We could use the help! Considering your are experienced in Java and has experience with Spigot/Bukkit.

**Comment by ThunderGemios10** [comment]
@Willsr71 Do you have Skype? So we can chat live.

**Comment by Willsr71** [comment]
I refuse to install skype because I am a paranoid freak when it comes to that, however I do have teamspeak servers hosted at ts3.noxal.net and ts3.preludecraft.com (preludecraft one is going down later today). On the other note, I would be happy to join the development.

**Comment by ThunderGemios10** [comment]
@Willsr71 Ok then? You should get an invitation now.

**Comment by Willsr71** [comment]
Got it. I have set up jenkins in such a way that everyone who has access to this repository should by default have access to the clither-server and clither-api projects on jenkins. Just sign in with your github account and you should be set.

**Comment by ThunderGemios10** [comment]
All right ! Make the changes to pom.xml now.

**Comment by Willsr71** [comment]
That took way too long. Everything is working now. Closing this.
