### ISSUE TITLE
Basic guide

### ISSUE THREAD

**Issue by Ciao121** [ClitherProject/Clither-Server#6]
Hi,
can someone please write a short howto for those (like me) who are really  noob to java? I.e. how to execute the server.

I triet starting clither-server-1.0-SNAPSHOT.jar but when I try i get this in the log

`17:04:06 [INFO] Clither is now starting.
17:04:06 [INFO] Loading plugins.
17:04:06 [INFO] Enabling plugins.
17:04:06 [INFO] Start listening on port 443
17:04:06 [INFO] Server successfully started on port 443.
17:04:22 [INFO] /127.0.0.1 (60868) has connected to the server!
17:04:22 [INFO] /127.0.0.1 (60868) has connected to the server!
17:04:24 [INFO] /127.0.0.1 (60871) has connected to the server!
17:04:24 [INFO] /127.0.0.1 (60871) has connected to the server!
17:04:24 [INFO] /127.0.0.1 (60868) has disconnected from the server!
17:04:25 [INFO] /127.0.0.1 (60871) has disconnected from the server!
17:04:25 [INFO] /127.0.0.1 (60872) has connected to the server!
17:04:25 [INFO] /127.0.0.1 (60872) has connected to the server!
17:04:28 [INFO] /127.0.0.1 (60872) has disconnected from the server!
17:05:05 [INFO] /127.0.0.1 (60921) has connected to the server!
17:05:05 [INFO] /127.0.0.1 (60921) has connected to the server!
17:05:08 [INFO] /127.0.0.1 (60921) has disconnected from the server!
17:05:08 [INFO] /127.0.0.1 (60922) has connected to the server!
17:05:08 [INFO] /127.0.0.1 (60922) has connected to the server!
17:05:11 [INFO] /127.0.0.1 (60922) has disconnected from the server!
17:05:11 [INFO] /127.0.0.1 (60923) has connected to the server!
17:05:11 [INFO] /127.0.0.1 (60923) has connected to the server!
17:05:14 [INFO] /127.0.0.1 (60923) has disconnected from the server!
17:05:14 [INFO] /127.0.0.1 (60924) has connected to the server!
17:05:14 [INFO] /127.0.0.1 (60924) has connected to the server!
17:05:17 [INFO] /127.0.0.1 (60924) has disconnected from the server!`

But nothing happen on the client side and at the end the client connects to an external server.

Thank you!

**Comment by ThunderGemios10** [comment]
@Ciao121 As of now, Networking isn't working right now.. We are currently developing it, so you may have to wait.

**Comment by Ciao121** [comment]
Oh ok. I was thinking was my fault. Thanks!!!
